version: '2.0'

services:
  app:
    #image: xmarlem/das-boot:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "ENVIRONMENT=test"
#    depends_on:
#      - db
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  #    - "~/.m2/:/root/.m2/"
  #    - "$PWD:$PWD"
    command:
      dockerize -wait tcp://db:5432 -timeout 240s mvn "-Dtest=ShipwreckControllerWebIntegrationTest" "-Dspring.profiles.active=test" verify
      #dockerize -wait tcp://db:5432 -timeout 240s /usr/share/maven/mvn --version

  db:
    image: xmarlem/docker-postgres
    ports:
      - "5432:5432"
    #expose:
    #  - "5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres@123
      - POSTGRES_DB=dasboot
#
