version: '3'

services:
  app:
    image: xmarlem/das-boot
    ports:
      - "8080:8080"
    #  - spring.datasource.url=jdbc:postgresql://192.168.99.102:5432/dasboot
    #command: -Dspring.datasource.url=jdbc:postgresql://192.168.99.102:5432/dasboot
    environment:
      - "ENVIRONMENT=test"
#    depends_on:
#      - db
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  db:
    image: xmarlem/docker-postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres@123
      - POSTGRES_DB=dasboot
#
