version: '3.6'

services:
  test:
    build: .
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: dockerize -wait tcp://app:8080 -timeout 240s ${M3_HOME}/bin/mvn -Dtest=SeleniumContainerTest.java -Dspring.profiles.active=test test
  app:
    #image: xmarlem/das-boot:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "ENVIRONMENT=test"
#    depends_on:
#      - db
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: dockerize -wait tcp://db:5432 java -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=test -jar /das-boot-0.0.1-SNAPSHOT.jar
  db:
    image: xmarlem/docker-postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres@123
      - POSTGRES_DB=dasboot
#
