version: '3.6'

services:
  app:
    #image: xmarlem/das-boot:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    #  - spring.datasource.url=jdbc:postgresql://192.168.99.102:5432/dasboot
    #command: -Dspring.datasource.url=jdbc:postgresql://192.168.99.102:5432/dasboot
    environment:
      - "ENVIRONMENT=test"
#    depends_on:
#      - db
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: dockerize -wait tcp://db:5432 java -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=$ENVIRONMENT -jar /das-boot-0.0.1-SNAPSHOT.jar
  db:
    image: xmarlem/docker-postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres@123
      - POSTGRES_DB=dasboot
#
